spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

jwt:
  expiration:
    time: 120
  public:
    key: classpath:asd.pub
  private:
    key: classpath:asd.key
server:
  error:
    include-message: always
