POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "userName": "thomas",
  "firstName": "thomas",
  "lastName": "nachname",
  "password" : "auto2413"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userName": "thomas",
  "password" : "auto2413"
}

> {%
    client.global.set("auth_token", response.body.authToken);
%}

###
GET http://localhost:8080/my/user
Authorization: Bearer {{auth_token}}
