# create a user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "userName": "dwight_rocks",
  "firstName": "Dwight",
  "lastName": "Shrute",
  "password": "auto2413"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userName": "dwight_rocks",
  "password": "wrongPassword"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userName": "dwight_rocks",
  "password": "wrongPassword"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userName": "dwight_rocks",
  "password": "wrongPassword"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "userName": "dwight_rocks",
  "password": "wrongPassword"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 400);
});
client.test("Error message is thrown", function () {
client.assert(response.body.message.startsWith("locked"));
});
%}
