name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: asd-usermanager-be
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build
        run: gradle build -x test
      - name: Test
        run: gradle test
